version: "3.9"
services:
  runner:
    build:
      context: ../game-runner
      dockerfile: multi-stage.Dockerfile
    container_name: GameRunner
    networks:
      - network
    environment:
      BOT_COUNT:  1
    ports:
      - "5000:5000"
  engine:
    build:
      context: ../game-engine
      dockerfile: multi-stage.Dockerfile
    container_name: GameEngine
    networks:
      - network
    environment:
      RunnerIp: runner # Should be the Docker Compose service name used for the runner.
      LOG_LEVEL: info
      BOT_COUNT: 1
    depends_on:
      - "runner"
      - "logger"
  logger:
    build:
      context: ../game-logger
      dockerfile: multi-stage.Dockerfile
    container_name: GameLogger
    networks:
      - network
    environment:
      RUNNER_IPV4: runner
      MATCH_STATUS_FILE: matchState.log
      GAME_COMPLETE_FILE: gameComplete.log
    depends_on:
      - "runner"
networks:
  network: